version: '3.8'
services: 
    app:
        build: ./
        restart: unless-stopped
        env_file: ./.env
        container_name: $CONTAINER_NAME
        ports:
            - $PORT:$PORT
        stdin_open: true
        tty: true